version: '3.3'

services:
  web_api_flask:
    build:
      context: ./
      dockerfile: build/Dockerfile
    ports:
      - "50000:5000"
    volumes:
      - ./app:/app
    command: ["python", "main.py"]
